services:
  - type: web
    name: flask-postgres-api
    env: python
    repo: https://github.com/uwidcit/flaskmvc.git
    plan: free
    branch: main
    healthCheckPath: /healthcheck
    buildCommand: "pip install -r requirements.txt && flask db upgrade"  # Make sure your Flask app uses Flask-Migrate or similar for DB migrations
    startCommand: "flask init && gunicorn wsgi:app"  # Ensure you run flask init before starting the app
    envVars:
      - fromGroup: flask-postgres-api-settings
      - key: POSTGRES_URL
        fromDatabase:
          name: flask-postgres-api-db
          property: host
      - key: POSTGRES_USER
        fromDatabase:
          name: flask-postgres-api-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: flask-postgres-api-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: flask-postgres-api-db
          property: database 

envVarGroups:
  - name: flask-postgres-api-settings
    envVars:
      - key: ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production  # Make sure to set this to production or development

databases:
  - name: flask-postgres-api-db
    plan: free
    databaseName: mydb  # Ensure this matches the database name in your app
