services:
  - type: web
    name: flask-postgres-api
    env: python
    repo: https://github.com/uwidcit/flaskmvc.git
    plan: free
    branch: main
    healthCheckPath: /healthcheck
    buildCommand: "flask db upgrade && gunicorn wsgi:app"
    startCommand: "flask init && gunicorn wsgi:app"  
    envVars:
      - fromGroup: flask-postgres-api-settings
      - key: POSTGRES_URL
        fromDatabase:
          name: flask-postgres-api-db
          property: host
      - key: POSTGRES_USER
        fromDatabase:
          name: flask-postgres-api-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: flask-postgres-api-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: flask-postgres-api-db
          property: database 

envVarGroups:
  - name: flask-postgres-api-settings
    envVars:
      - key: ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production  

databases:
  - name: flask-postgres-api-db
    plan: free
    databaseName: mydb 
